export const ENDLOADING_PKMN = 'ENDLOADING_PKMN';
export const LOADING_PKMN = 'LOADING_PKMN';

export const FILTER_PKMN = 'FILTER_PKMN';
export const FILTER_FAVORITES_PKMN = 'FILTER_FAVORITES_PKMN';


export const FETCH_PKMN = 'FETCH_PKMN';
export const DETAILS_PKMN = 'DETAILS_PKMN';
export const TOGGLE_FAVORITE_PKMN = 'TOGGLE_FAVORITE_PKMN';

export const CHANGE_SEGCONTROL_PKMN = 'CHANGE_SEGCONTROL_PKMN';